# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
add_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/test/add.coe
add_files /afs/ece.cmu.edu/usr/wpe/Downloads/multiply.coe
read_verilog {
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_localparams.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_functions.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/tb/global_defines.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_config_defines.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/memory_configuration.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/register_addresses.vh
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/system_config_defines.vh
}
read_ip /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

read_ip /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_bootrom/blk_mem_gen_bootrom.xci
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_bootrom/blk_mem_gen_bootrom_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_bootrom/blk_mem_gen_bootrom.xci]

read_ip /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_shifter.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/lib/generic_sram_line_en.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/lib/generic_sram_byte_en.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_tagstore.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_reservation.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_register_bank.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_barrel_shift.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_alu.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_wishbone_buf.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_icache.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_execute_mem.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_dispatch.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_execute_multiply.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_execute_alu.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_decode.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_wishbone.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/amber25/a25_fetch.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/545/b01_core.sv
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/uart.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/interrupt_controller.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/wishbone_arbiter.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/system.v
}
read_verilog -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/timer_module.v
  /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/sources_1/imports/system/test_module.v
}
read_xdc /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/constrs_1/imports/drra/amber_constraints_fakeddr3.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/wpe/Private/545/beryl/beryl.srcs/constrs_1/imports/drra/amber_constraints_fakeddr3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system -part xc7vx485tffg1761-2
write_checkpoint -noxdef system.dcp
catch { report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb }
