# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.cache/wt [current_project]
set_property parent.project_path /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
read_ip /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_verilog -library xil_defaultlib -sv /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/sources_1/new/ddr.sv
read_xdc /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/DRRA/545Project/Labs/Lab_2/Lab_2/Lab_2.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ddr -part xc7vx485tffg1761-2 -flatten_hierarchy none
write_checkpoint -noxdef ddr.dcp
catch { report_utilization -file ddr_utilization_synth.rpt -pb ddr_utilization_synth.pb }
